maman11: my_string.o count_bits.o
	gcc -Wall -ansi -pedantic -g my_string.o -o my_string
	gcc -Wall -ansi -pedantic -g count_bits.o -o count_bits
maman11.o: my_string.c count_bits.c
	gcc -c -ansi -Wall my_string.c -o my_string.o
	gcc -c -ansi -Wall count_bits.c -o count_bits.o

